import random

BOARD_HEIGHT = 24
BOARD_WIDTH = 10

DEFAULT_SEED = 31

print("SEED BELOW IS: ",DEFAULT_SEED)
#DEFAULT_SEED = 42
#DEFAULT_SEED = 1
#DEFAULT_SEED = random.randint(1,100)

BLOCK_LIMIT = 400

INTERVAL = 1000

PREFIX = '<TETRIS WIRE PROTOCOL>'
